name: build

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup java
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '17.0.9+9'

            - name: Build
              run: |
                  chmod +x ./gradlew
                  ./gradlew
